### ISSUE TITLE
Day on Lobster Boat

### ISSUE THREAD

**Issue by EricDesjardins** [Open-Water-Logger/WOWL#1]
Details for our trip to Harpswell ME on 10/7/21:

Meeting with Dana (207-210-0015) @ 6AM at the Interstate Lobster Dock

Need to wear: Warm, wind-proof layers and muck boots

Need to bring: 
- Notebook and pen
- Stopwatch
- Waterproof phone case
- Disc golf bags (just in case)
- Cooler (for lobsters, hopefully)
- Raincoat
- Warm hat
- Sunglasses
- Waterproof Camera
- Lunch and Drink
- Gift for Dana

**Comment by dsully-dev** [comment]
I'll edit your list if I think of anything else. Thanks @EricDesjardins!
